### ISSUE TITLE
investigate oracle jdbc jar upgrade

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko-persistence-jdbc#112]
Upgrading to using oracle jdbc8 instead of jdbc6 runs into trouble.

https://github.com/apache/incubator-pekko-persistence-jdbc/actions/runs/7862784116/job/21452649793

* We might need to upgrade the oracle db image.
* We might need to change our code
* We are testing with an old jar and we should try to use a newer one

```
[info]   Cause: java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1
[info] ORA-01882: timezone region not found
[info]   at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
[info]   at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:441)
[info]   at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:436)
[info]   at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1110)
[info]   at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:552)
[info]   at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:540)
[info]   at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:256)
[info]   at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:501)
[info]   at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1297)
[info]   at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:694)
[info]   at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:782)
[info]   at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
[info]   at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:704)
[info]   at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
[info]   at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
[info]   at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
[info]   at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
[info]   at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
[info]   at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
[info]   at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
```

**Comment by Roiocam** [comment]
Seems like has been solved in #157, wdyt @pjfanning ?
