### ISSUE TITLE
Slick 3.5.1 leads to startup crashes 

### ISSUE THREAD

**Issue by Roiocam** [apache/pekko-persistence-jdbc#201]
## Reproducer

Just use the latest release: 1.1.0-M1-RC1.

## Stack Trace

```
Caused by: java.lang.NoClassDefFoundError: scala/reflect/api/Trees$TreeApi
        at slick.lifted.AnyOptionExtensionMethods$.getOrElse$extension(ExtensionMethods.scala:219)
        at org.apache.pekko.persistence.jdbc.query.dao.ReadJournalQueries.<init>(ReadJournalQueries.scala:33)
        at org.apache.pekko.persistence.jdbc.query.dao.DefaultReadJournalDao.<init>(DefaultReadJournalDao.scala:42)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.apache.pekko.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:50)
        at scala.util.Try$.apply(Try.scala:210)
        at org.apache.pekko.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:45)
        at org.apache.pekko.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$5(ReflectiveDynamicAccess.scala:58)
        at scala.util.Success.flatMap(Try.scala:258)
        at org.apache.pekko.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:57)
        at org.apache.pekko.persistence.jdbc.query.scaladsl.JdbcReadJournal.<init>(JdbcReadJournal.scala:86)
        at org.apache.pekko.persistence.jdbc.query.JdbcReadJournalProvider.scaladslReadJournal(JdbcReadJournalProvider.scala:25)
        at org.apache.pekko.persistence.jdbc.query.JdbcReadJournalProvider.scaladslReadJournal(JdbcReadJournalProvider.scala:22)
        at org.apache.pekko.persistence.query.PersistenceQuery$$anon$1.scalaDsl(PersistenceQuery.scala:42)
        at org.apache.pekko.persistence.query.PersistenceQuery$$anon$1.scalaDsl(PersistenceQuery.scala:41)
        at org.apache.pekko.persistence.PersistencePlugin$$anon$1.createExtension(PersistencePlugin.scala:71)
        at org.apache.pekko.persistence.PersistencePlugin$$anon$1.createExtension(PersistencePlugin.scala:68)
        at org.apache.pekko.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1176)
        at org.apache.pekko.actor.ExtensionId.apply(Extension.scala:87)
        at org.apache.pekko.actor.ExtensionId.apply$(Extension.scala:86)
        at org.apache.pekko.persistence.PersistencePlugin$$anon$1.apply(PersistencePlugin.scala:68)
        at org.apache.pekko.persistence.PersistencePlugin.pluginFor(PersistencePlugin.scala:66)
        at org.apache.pekko.persistence.query.PersistenceQuery.getReadJournalFor(PersistenceQuery.scala:79)
        at org.apache.pekko.persistence.query.PersistenceQuery.getReadJournalFor(PersistenceQuery.scala:82)
        at com.iquantex.phoenix.lite.console.service.OffsetStateService.<init>(OffsetStateService.java:37)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170)
        ... 42 common frames omitted
Caused by: java.lang.ClassNotFoundException: scala.reflect.api.Trees$TreeApi
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 75 common frames omitted

```

## Probably related

https://github.com/slick/slick/issues/2933

## Downgrade verification

after downgrading to 3.3.3 and then publishing to my local m2 repo, it solves the startup issue.

**Comment by pjfanning** [comment]
pekko-connectors-slick and pekko-projection-slick may also be affected.

It's a pity that a Slick 3.5.2 has not been released with this change.
